Select Distinct 
EMPL.PERSON_NUMBER as "PERSON NUMBER",
J.EFFECTIVE_START_DATE,
J.EFFECTIVE_END_DATE,
J.LAST_UPDATE_DATE,
J.LAST_UPDATED_BY,
J.ASSIGNMENT_NUMBER as "ASSIGNMENT_NUMBER",
J.ACTION_CODE as "ACTION_CODE",
J.ASSIGNMENT_NAME as "JOB_NAME",
J.ASSIGNMENT_STATUS_TYPE as "ASSIGNMENT_STATUS_TYPE",
J.REASON_CODE as "REASON_CODE",
POS.WORKER_NUMBER as "Old Empoloyee ID"
,NVL(PU.FIRST_NAME,' ') as "First name"
,NVL(PU.MIDDLE_NAMES,' ') as "Middle name"
,NVL(PU.LAST_NAME,' ') as "Last name"

,(SELECT DISTINCT DISPLAY_NAME
   FROM PER_PERSON_NAMES_F
   WHERE PERSON_ID = C.MANAGER_ID
   AND ROWNUM      = 1
   ) as "Manager Name"

,NVL(LE1.NAME,' ') as "Business Unit"

,(CASE ORG.NAME
	 When 'Management' THEN ''
	 When 'Human Resources' THEN ''
When 'Administration' THEN ''
Else ORG.NAME
	 End) as "Sub Department",
	 

NVL(Substr(ORG.NAME,1,LENGTH(ORG.NAME) - LENGTH(substr(ORG.NAME,INSTR(ORG.NAME,'-',1),50))), SUBSTR (ORG.NAME, INSTR(ORG.NAME,'-',1),50)) as DEPARTMENT
 
 



FROM 
PER_ALL_ASSIGNMENTS_M J,
PER_ALL_PEOPLE_F_V EMPL,
PER_PERIODS_OF_SERVICE POS,
per_person_names_f PU,
PER_ASSIGNMENT_SUPERVISORS_F C,
HR_ORGANIZATION_UNITS_F_TL LE1,
PER_DEPARTMENTS ORG




Where

J.PERSON_ID=EMPL.PERSON_ID
and	 J.PRIMARY_FLAG ='Y'
AND J.PRIMARY_WORK_RELATION_FLAG = 'Y'
and J.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'

AND J.PERSON_ID  = POS.PERSON_ID(+)
AND POS.Last_update_date =(SELECT MAX(POS1.Last_update_date) FROM PER_PERIODS_OF_SERVICE POS1  WHERE POS.PERSON_ID= POS1.PERSON_ID AND POS1.Last_update_date <= sysdate)

and PU.name_type = 'GLOBAL'
AND PU.person_id = J.person_id
AND TRUNC(sysdate) BETWEEN PU.EFFECTIVE_START_DATE AND PU.EFFECTIVE_END_DATE

AND J.ASSIGNMENT_ID  = C.ASSIGNMENT_ID (+)
AND C.PERSON_ID (+) = J.PERSON_ID
AND C.EFFECTIVE_START_DATE =(SELECT MAX(C1.EFFECTIVE_START_DATE) FROM PER_ASSIGNMENT_SUPERVISORS_F C1  WHERE C1.PERSON_ID= C.PERSON_ID AND C1.EFFECTIVE_START_DATE <= Sysdate)

AND J.BUSINESS_UNIT_ID=LE1.ORGANIZATION_ID (+)
and LE1.EFFECTIVE_START_DATE = (SELECT MAX(LE2.EFFECTIVE_START_DATE) FROM HR_ORGANIZATION_UNITS_F_TL LE2 WHERE LE1.ORGANIZATION_ID = LE2.ORGANIZATION_ID)

and J.ORGANIZATION_ID = ORG.ORGANIZATION_ID
and ORG.EFFECTIVE_START_DATE = (SELECT MAX(ORG1.EFFECTIVE_START_DATE) FROM PER_DEPARTMENTS ORG1 WHERE ORG1.ORGANIZATION_ID = ORG.ORGANIZATION_ID and ORG1.EFFECTIVE_START_DATE <= SYSDATE)

AND J.LEGISLATION_CODE='MY'

Order By EMPL.PERSON_NUMBER, J.EFFECTIVE_START_DATE